blank_issues_enabled: true

contact_links:
  - name: ğŸ’¬ Forum
    url: https://github.com/project-zetton/zetton-stream/discussions
    about: Ask general usage questions and discuss with other zetton-stream community members
  - name: ğŸŒ Explore Project Zetton
    url: https://github.com/project-zetton
    about: Get know more about Project Zetton
